apiVersion: apps/v1;
kind: Deployment 
metadata:
  name: moovex-deployment
  labels: 
    app: moovex
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: moovex
  template:
    metadata: 
      labels: 
        app: moovex
    spec:
      containers:
      - name: kkunle/moovex
        image: kkunle/moovex:latest
        ports:
        - containerPort: 3000

